export const CATEGORY_LOADED = 'CATEGORY_LOADED';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_SAVED = 'CATEGORY_SAVED';
export const CATEGORY_DELETED = 'CATEGORY_DELETED';

export const PRODUCT_LOADED = 'PRODUCT_LOADED';
export const PRODUCT_ADD = 'PRODUCT_ADD';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const PRODUCT_SAVED = 'PRODUCT_SAVED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';

export const VENDOR_LOADED = 'VENDOR_LOADED';
export const VENDOR_ADD = 'VENDOR_ADD';
export const VENDOR_EDIT = 'VENDOR_EDIT';
export const VENDOR_SAVED = 'VENDOR_SAVED';
export const VENDOR_DELETED = 'VENDOR_DELETED';

export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';